lint:
  files_exist:
    - conf/modules.config
  files_unchanged:
    - .github/PULL_REQUEST_TEMPLATE.md
    - assets/multiqc_config.yaml
    - .github/workflows/linting.yml
repository_type: pipeline
